# Generated by Django 5.0 on 2023-12-18 04:59

import angara_vehicles_app.models
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.00'), max_digits=19)),
                ('weight', models.BigIntegerField()),
                ('city_production', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('image_path', models.TextField()),
                ('manufacturing_ccompany', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(1, 'Удален'), (2, 'Действует')])),
                ('component_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('engine_name', models.CharField(blank=True, max_length=255, null=True)),
                ('total_thrust', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('dry_weight', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('combustion_chamber_pressure', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
            ],
            options={
                'verbose_name_plural': 'Components',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.CharField(max_length=500, unique=True)),
                ('password', models.CharField(blank=True, max_length=500, null=True)),
                ('is_moderator', models.BooleanField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Users',
                'managed': True,
            },
            managers=[
                ('objects', angara_vehicles_app.models.NewUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Черновик'), (2, 'Удален'), (3, 'Сформирован'), (4, 'Завершен'), (5, 'Отклонен')])),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('formation_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('id_creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications_customer_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Applications',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ApplicationsComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('components_amount', models.IntegerField()),
                ('id_application', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='angara_vehicles_app.applications')),
                ('id_component', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='angara_vehicles_app.components')),
            ],
            options={
                'managed': True,
                'unique_together': {('id_component', 'id_application')},
            },
        ),
    ]
